(require 'ert)
(require 'yf)

(ert-deftest yf-arithmetics-test ()
  (should (equal (yf-eval-postfix "1 1 +")
             '((2 . "ANY"))))
  (should (equal (yf-eval-postfix "1 -1 +")
             '((0 . "ANY"))))
  (should (equal (yf-eval-postfix "-10 -20 +")
             '((-30 . "ANY"))))
  (should (equal (yf-eval-postfix "1 0 -")
             '((1 . "ANY"))))
  (should (equal (yf-eval-postfix "-10 5 -")
             '((-15 . "ANY"))))
  (should (equal (yf-eval-postfix "10 2 -")
             '((8 . "ANY"))))
  (should (equal (yf-eval-postfix "3 10 -")
             '((-7 . "ANY"))))
  (should (equal (yf-eval-postfix "40 3 -")
             '((37 . "ANY"))))
  (should (equal (yf-eval-postfix "4 3 *")
             '((12 . "ANY"))))
  (should (equal (yf-eval-postfix "2 3 +")
             '((5 . "ANY")))))

(ert-deftest yf-sum-test ()
  (should (equal (yf-eval-postfix "sum") '()))
  (should (equal (yf-eval-postfix "10 sum")
             '((10 . "ANY"))))
  (should (equal (yf-eval-postfix "2 3 4 5 sum")
             '((14 . "ANY")))))

(ert-deftest yf-stack-test ()
  (should (equal (yf-eval-postfix "4 dup")
             '((4 . "ANY") (4 . "ANY"))))
  (should (equal (yf-eval-postfix "3 dup *")
             '((9 . "ANY"))))
  (should (equal (yf-eval-postfix "6 7 swap")
             '((6 . "ANY") (7 . "ANY"))))
  (should (equal (yf-eval-postfix "6 7 swap swap")
             '((7 . "ANY") (6 . "ANY"))))
  (should (equal (yf-eval-postfix "3 7 swap -")
             '((4 . "ANY"))))
  (should (equal (yf-eval-postfix "1 2 over")
             '((1 . "ANY") (2 . "ANY") (1 . "ANY"))))
  (should (equal (yf-eval-postfix "3 drop") nil)))
             
(ert-deftest yf-depth-test ()
  (should (equal (yf-eval-postfix "depth")
             '((0 . "ANY"))))
  (should (equal (yf-eval-postfix "0 depth")
             '((1 . "ANY") (0 . "ANY"))))
  (should (equal (yf-eval-postfix "1 1 1 1 depth")
             '((4 . "ANY")
               (1 . "ANY") (1 . "ANY") (1 . "ANY") (1 . "ANY")))))

(ert-deftest yf-clear-test ()
  (should (equal (yf-eval-postfix "1 2 3 4 5 clear depth")
             '((0 . "ANY")))))
