name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install emacs (Linux)
        uses: purcell/setup-emacs@master
        with:
          version: 28.2

      - uses: leotaku/elisp-check@master
        with:
         check: ert
         file: test/yf-test.el

