name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.2
          
      - name: Install dependencies
        run: |
          emacs -Q --batch --eval "(package-initialize)" \
                --eval "(package-refresh-contents)" \
                --eval "(package-install 'request)" \
                --eval "(package-install 'json)" \
                
      - uses: leotaku/elisp-check@master
        with:
         check: ert
         file: test/yf-test.el

